services:
  jekyll-site:
    image: jekyll-site
    build: .
    volumes:
      - .:/usr/src/app
      - bundle_cache:/usr/local/bundle
    ports: [ 4000:4000 ]
    user: 1000:1000
    environment: [ JEKYLL_ENV=docker ]
    command: jekyll serve -H 0.0.0.0 -w --config _config.yml,_config_docker.yml

volumes:
  bundle_cache:
